/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.knjiga;

import controller.ClientController;
import domain.Autor;
import domain.Knjiga;
import form.FrmMain;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FrmUpdateKnjiga extends javax.swing.JDialog {

    /**
     * Creates new form FrmUpdateKnjiga
     */
    Knjiga knjiga;
    public FrmUpdateKnjiga(java.awt.Frame parent, boolean modal, Knjiga knjiga) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Izmeni knjigu");
        this.knjiga=knjiga;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtZanr = new javax.swing.JTextField();
        cmbAutor = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JFormattedTextField();
        btnAzuriraj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGodina = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNaslov = new javax.swing.JTextField();
        txtIzdavac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnAzuriraj.setText("Sacuvaj knjigu");
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        jLabel2.setText("Izdavac:");

        jLabel7.setText("Godina izdanja:");

        jLabel3.setText("Naslov:");

        txtGodina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel4.setText("Zanr:");

        jLabel5.setText("Autor:");

        jLabel6.setText("Kolicina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                            .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIzdavac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtZanr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnAzuriraj))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22)
                            .addComponent(txtKolicina))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtGodina)))
                    .addGap(32, 32, 32)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmbAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtKolicina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addComponent(btnAzuriraj)
                    .addGap(1, 1, 1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed
        try {

            if(txtNaslov.getText().isEmpty()||txtIzdavac.getText().isEmpty()||txtZanr.getText().isEmpty()||txtGodina.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da kreira novu knjigu", "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(Integer.parseInt(txtKolicina.getText())<0){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da kreira novu knjigu", "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            Knjiga k=new Knjiga(knjiga.getId(), txtNaslov.getText(), txtIzdavac.getText(), Integer.parseInt(txtGodina.getText()),
                txtZanr.getText(), (Autor) cmbAutor.getSelectedItem(), Integer.parseInt(txtKolicina.getText()));
           
            
           
            
            if(k.getId()==knjiga.getId() && k.getNaslov().equals(knjiga.getNaslov())&&k.getIzdavac().equals(knjiga.getIzdavac())&&
                   k.getGodinaIzdanja()==knjiga.getGodinaIzdanja()&&k.getZanr().equals(knjiga.getZanr())&&k.getAutor().getId()==knjiga.getAutor().getId()
                    &&k.getKolicina()==knjiga.getKolicina() ){
                
                JOptionPane.showMessageDialog(this,"Izmena nije izvrsena.");
                this.dispose();
                return;
            }
            ClientController.getInstance().updateKnjiga(k);
            JOptionPane.showMessageDialog(this,"Sistem je izmenio knjigu");
            
            FrmMain main = (FrmMain) getParent();
	    main.refreshTableKnjiga();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Sistem ne moze izmeni knjigu", "Error",
                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmAddKnjiga.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Sistem ne moze izmeni knjigu", "Error",
                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmAddKnjiga.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAzurirajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JComboBox cmbAutor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField txtGodina;
    private javax.swing.JTextField txtIzdavac;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JTextField txtNaslov;
    private javax.swing.JTextField txtZanr;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        
        txtNaslov.setText(knjiga.getNaslov());
        txtIzdavac.setText(knjiga.getIzdavac());
        txtZanr.setText(knjiga.getZanr());
        txtNaslov.setText(knjiga.getNaslov());
        txtNaslov.setText(knjiga.getNaslov());
        txtGodina.setText(String.valueOf(knjiga.getGodinaIzdanja()));
        txtKolicina.setText(String.valueOf(knjiga.getKolicina()));
        
        
        try {
            List<Autor> listaAutora=ClientController.getInstance().getAllAutor();
            cmbAutor.removeAllItems();
            for (Autor autor : listaAutora) {
                cmbAutor.addItem(autor);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmAddKnjiga.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(knjiga.getAutor().getId());
        cmbAutor.setSelectedItem(knjiga.getAutor());
        
    }
}
