/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form.pozajmica;

import controller.ClientController;
import domain.Pozajmica;
import form.FrmMain;
import form.components.TableModelPozajmica;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FrmFindPozajmica extends javax.swing.JDialog {

    /**
     * Creates new form FrmFindPozajmica
     */
    
    private FrmMain frmMain;
    
    public FrmFindPozajmica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi pozajmice");
        TableModelPozajmica tm= new TableModelPozajmica();
        Thread thread=new Thread(tm);
        thread.start();
        tblPozajmica.setModel(tm);
        
        if (parent instanceof FrmMain) {
            this.frmMain = (FrmMain) parent; // čuvamo referencu
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPozajmica = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnProduzi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        tblPozajmica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPozajmica);

        btnIzmeni.setText("Izmeni pozajmicu");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnProduzi.setText("Produzi pozajmicu");
        btnProduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduziActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi pozajmicu");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduzi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi))
                    .addComponent(txtPretraga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnProduzi)
                    .addComponent(btnObrisi))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String parametar=txtPretraga.getText();
        TableModelPozajmica tm= (TableModelPozajmica)tblPozajmica.getModel();
            tm.setParametar(parametar);
            if(tm.getRowCount()==0){
                JOptionPane.showMessageDialog(this,
                        "Sistem ne moze da nadje pozajmice po zadatoj vrednosti",
                        "Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
      
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnProduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduziActionPerformed
        int rowIndex=tblPozajmica.getSelectedRow();
        if(rowIndex>=0){
            try {
                SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
                TableModelPozajmica tm=(TableModelPozajmica) tblPozajmica.getModel();
                Pozajmica osnovna= tm.getPozajmica(rowIndex);
                Pozajmica pozajmica=ClientController.getInstance().getPozajmica(osnovna);
                
                
                Calendar calendar = Calendar.getInstance();
                Date date = pozajmica.getRokVracanja(); 
                
                long razlika= (date.getTime()-pozajmica.getDatumIzdavanja().getTime())/(1000*60*60*24);
                System.out.println(razlika);
                if(razlika>=40){
                     JOptionPane.showMessageDialog(this,
                            "Zaduzenje ne moze biti produzeno vise od jedanput","Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                calendar.setTime(date);
                int daysToAdd = 20;
                calendar.add(Calendar.DAY_OF_MONTH, daysToAdd); 
                Date newDate = calendar.getTime();
                
                
                
                pozajmica.setRokVracanja(newDate);
                

                ClientController.getInstance().updatePozajmica(pozajmica);
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Niste odabrali nijednu uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProduziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        TableModelPozajmica tm = (TableModelPozajmica) tblPozajmica.getModel();
        int rowIndex = tblPozajmica.getSelectedRow();
        if (rowIndex >= 0) {
            int deleteYesNo = JOptionPane.showConfirmDialog(this,
                    "Da li ste sigurni da zelite da obrisete ovu pozajmicu?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

            if (deleteYesNo == JOptionPane.NO_OPTION) {
                return;
            }

            if (deleteYesNo == JOptionPane.YES_OPTION) {
                try {
                    Pozajmica pozajmica = tm.getPozajmica(rowIndex);
                   
                    ClientController.getInstance().deletePozajmica(pozajmica);
                    refreshTable();
                    if (frmMain != null) {
                    frmMain.refreshTableKnjiga(); // osvežavanje na glavnoj formi
                }
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao pozajmicu");
                    
                } catch (Exception ex) {
                    Logger.getLogger(FrmFindPozajmica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise uslugu", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFindPozajmica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFindPozajmica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFindPozajmica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFindPozajmica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmFindPozajmica dialog = new FrmFindPozajmica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnProduzi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPozajmica;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
       TableModelPozajmica tm= (TableModelPozajmica) tblPozajmica.getModel();
        tm.refreshTable();
    }
    
}
